name: Clang #give this pipeline an actual name
on: push
jobs:
  C:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang compiler
        run: sudo apt-get install clang
      - name: Build targets using compiler
        run: |
          cd ./.testing/
          make -f Makefile COMP=clang
